#!/usr/bin/env php
<?php

use PoracleJS\PoracleJS\Telegram\Command\Member\CheckCommand;
use Symfony\Component\Console\Application;

require_once __DIR__ . '/vendor/autoload.php';

$app = new Application();

$app->add(new CheckCommand());

$app->run();
